### PR TITLE
fix: format py files with black

### PR DESCRIPTION
**Pull request by cpaniaguam**

### CODE REVIEW

**Comment by hollandjg** [comment]
This is great! Let's merge this one once we've merged everything else which is already done. Otherwise we're going to have to deal with tonnes of merge conflicts on every single file.

**Review by hollandjg — COMMENTED** [review]
This is great! Let's merge this one once we've merged everything else which is already done. Otherwise we're going to have to deal with tonnes of merge conflicts on every single file.

**Review by kmilo9999 — COMMENTED** [review]
I think we should only format the scripts in under the `source` folder. We have plans of removing the ones in the root folder.

**Comment by cpaniaguam** [comment]
> I think we should only format the scripts in under the `source` folder. We have plans of removing the ones in the root folder.
@kmilo9999 
Aren't more files from root/ going to bemoved to src or is that done?

**Comment by kmilo9999** [comment]
> > I think we should only format the scripts in under the `source` folder. We have plans of removing the ones in the root folder.
> 
> @kmilo9999 Aren't more files from root/ going to be moved to src or is that done?

I think whatever we dont need in the root folder should be removed form the project after we integrate the whole CLI.

**Comment by kmilo9999** [comment]
We should do this after the CLI full integration.

**Pull request closed without merging**
