### PR TITLE
Table of content in Readme

### PR DESCRIPTION
**Pull request by kmilo9999**
- Added table of contents in readme

### CODE REVIEW

**Comment by cpaniaguam** [comment]
@kmilo9999 What do you think about removing the deprecated sections?

**Comment by kmilo9999** [comment]
> @kmilo9999 What do you think about removing the deprecated sections?
Fine by me. @hollandjg ?

**Comment by hollandjg** [comment]
> > @kmilo9999 What do you think about removing the deprecated sections?
> > Fine by me. @hollandjg ?

Love it.

**Comment by kmilo9999** [comment]
> > > @kmilo9999 What do you think about removing the deprecated sections?
> > > Fine by me. @hollandjg ?
> 
> Love it.

So, removing those 2 sections from the table of content AND the readme ?  
I can put those at the end of the readme and the toc.

**Comment by cpaniaguam** [comment]
> > > > @kmilo9999 What do you think about removing the deprecated sections?
> > > > Fine by me. @hollandjg ?
> > 
> > 
> > Love it.
> 
> So, removing those 2 sections from the table of content AND the readme ? I can put those at the end of the readme and the toc.

I don't see a reason to keep them at all.

**Comment by kmilo9999** [comment]
Done!

**Review by cpaniaguam — APPROVED** [review]

**Pull request merged**
