### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by cpaniaguam**
Use Python 3.11 image and install project deps.

This could be used locally/remotely for development (using for example dev-containers in VS Code/ GittHub Code Spaces), for end-users, and for faster runs on CI.

### CODE REVIEW

**Comment by kmilo9999** [comment]
@cpaniaguam @hollandjg 
Can you remind me why we are keeping this PR opened?

**Comment by cpaniaguam** [comment]
> @cpaniaguam @hollandjg Can you remind me why we are keeping this PR opened?

Mainly to do faster CI runs as the current workflows install python and the other dependencies for the packages in each run. CI could run from a container from an image based on this Dockerfile.

**Comment by hollandjg** [comment]
I can't get this to build – there seems to be a problem when making the wheel for `Fiona`

**Review by hollandjg — CHANGES_REQUESTED** [review]
I've some changes to suggest in
- #173

**Comment by cpaniaguam** [comment]
I looked into hosting a docker image on CCV's account on docker hub. An action could be added to update the image upon merges to `main`. We did something like that in `IceFloeTracker.jl`. What do you think of that idea, @hollandjg?

**Comment by hollandjg** [comment]
> I looked into hosting a docker image on CCV's account on docker hub. An action could be added to update the image upon merges to `main`. We did something like that in `IceFloeTracker.jl`. What do you think of that idea, @hollandjg?

I'm sure we could, or we could put one on GHCR, but I'd be tempted just to stick with the Dockerfile – it doesn't take long to build the environment with the Dockerfile and the extra effort might not pay off. Maybe make it into an issue we could potentially solve later if it looks like it will be worth the extra effort?

**Review by hollandjg — APPROVED** [review]
Looks good to me!

**Review by kmilo9999 — COMMENTED** [review]
I managed to tested it in my docker installation. It works fine to me

**Pull request merged**
